# Change these first
owner: max-evia # Your GitHub organization or username, where this repository lives
repo: max-evia.github.io # The name of this repository

sites:
  - name: Evia Network Website
    url: https://www.evia.network
    assignees:
      - EviaNetwork
  - name: Evia Network DApp
    url: https://app.evia.network
    assignees:
      - EviaNetwork
  - name: Evia CosmoDash
    url: https://cosmodash.zone
    assignees:
      - EviaNetwork
  - name: Evia Network Docs
    url: https://docs.evia.network
    assignees:
      - EviaNetwork
  - name: Evia Network DApp API
    url: https://api.propel.evianetwork.com
    assignees:
      - max-evia
  - name: Evia CosmoDash API
    url: https://api.cosmodash.evia.network 
    assignees:
      - max-evia
  - name: KitKat Website
    url: https://www.kitkat.zone
    assignees:
      - EviaNetwork
  - name: KitKat Explorer
    url: https://explorer.kitkat.zone
    assignees:
      - EviaNetwork
  - name: KitKat Faucet API
    url: https://api.faucet.kitkat.zone
    assignees:
      - max-evia

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.evia.network
  # baseUrl: /max-evia.github.io
  logoUrl: https://raw.githubusercontent.com/evia-network/evia-network-assets/main/evia-logo-light-name.svg
  faviconSvg: https://raw.githubusercontent.com/evia-network/evia-network-assets/main/evia-favicon.svg
  name: 
  introTitle: "The official uptime monitor and status page for Evia Network Products and Services."
  introMessage: Find out the uptime status for your favorite Evia Network Product or Service. Any outages on our network should be visible here.
  navbar:
    - title: Home
      href: https://evia.network
    - title: App
      href: https://app.evia.network
    - title: Docs
      href: https://docs.evia.network
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/evia-network
  theme: ocean

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
